services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: configuracao-pretto
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/configuracao-pretto
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy && npm run seed && npm run start"

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata: